// Project querying
export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';

export const GET_PROJECT_PENDING = 'GET_PROJECT_PENDING';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR';

export const GET_PROJECT_ACTIONS_PENDING = 'GET_PROJECT_ACTIONS_PENDING';
export const GET_PROJECT_ACTIONS_SUCCESS = 'GET_PROJECT_ACTIONS_SUCCESS';
export const GET_PROJECT_ACTIONS_ERROR = 'GET_PROJECT_ACTIONS_ERROR';

// Project manipulation
export const ADD_PROJECT_PENDING = 'ADD_PROJECT_PENDING';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';

export const EDIT_PROJECT_PENDING = 'EDIT_PROJECT_PENDING';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR';

export const DELETE_PROJECT_PENDING = 'DELETE_PROJECT_PENDING';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';

// Project Completion
export const TOGGLE_PROJECT_COMPLETION_PENDING =
  'TOGGLE_PROJECT_COMPLETION_PENDING';
export const TOGGLE_PROJECT_COMPLETION_SUCCESS =
  'TOGGLE_PROJECT_COMPLETION_SUCCESS';
export const TOGGLE_PROJECT_COMPLETION_ERROR =
  'TOGGLE_PROJECT_COMPLETION_ERROR';

// Action querying
export const GET_ACTIONS_PENDING = 'GET_ACTIONS_PENDING';
export const GET_ACTIONS_SUCCESS = 'GET_ACTIONS_SUCCESS';
export const GET_ACTIONS_ERROR = 'GET_ACTIONS_ERROR';

// Action manipulation
export const ADD_ACTION_PENDING = 'ADD_ACTION_PENDING';
export const ADD_ACTION_SUCCESS = 'ADD_ACTION_SUCCESS';
export const ADD_ACTION_ERROR = 'ADD_ACTION_ERROR';

export const EDIT_ACTION_PENDING = 'EDIT_ACTION_PENDING';
export const EDIT_ACTION_SUCCESS = 'EDIT_ACTION_SUCCESS';
export const EDIT_ACTION_ERROR = 'EDIT_ACTION_ERROR';

export const DELETE_ACTION_PENDING = 'DELETE_ACTION_PENDING';
export const DELETE_ACTION_SUCCESS = 'DELETE_ACTION_SUCCESS';
export const DELETE_ACTION_ERROR = 'DELETE_ACTION_ERROR';

// Action Completion
export const TOGGLE_ACTION_COMPLETION_PENDING =
  'TOGGLE_ACTION_COMPLETION_PENDING';
export const TOGGLE_ACTION_COMPLETION_SUCCESS =
  'TOGGLE_ACTION_COMPLETION_SUCCESS';
export const TOGGLE_ACTION_COMPLETION_ERROR = 'TOGGLE_ACTION_COMPLETION_ERROR';
